import { Theme, type ThemeColor } from "@earendil-works/pi-coding-agent";

export function createCliTheme(): Theme {
  const fgEntries: Record<ThemeColor, string> = {
    accent: "#8bd5ff",
    border: "#6272a4",
    borderAccent: "#8bd5ff",
    borderMuted: "#44475a",
    success: "#50fa7b",
    error: "#ff5555",
    warning: "#f1fa8c",
    muted: "#bd93f9",
    dim: "#7f849c",
    text: "#f8f8f2",
    thinkingText: "#cba6f7",
    userMessageText: "#f8f8f2",
    customMessageText: "#f8f8f2",
    customMessageLabel: "#8bd5ff",
    toolTitle: "#8bd5ff",
    toolOutput: "#f8f8f2",
    mdHeading: "#8bd5ff",
    mdLink: "#8bd5ff",
    mdLinkUrl: "#7f849c",
    mdCode: "#f1fa8c",
    mdCodeBlock: "#f8f8f2",
    mdCodeBlockBorder: "#44475a",
    mdQuote: "#bd93f9",
    mdQuoteBorder: "#6272a4",
    mdHr: "#44475a",
    mdListBullet: "#8bd5ff",
    toolDiffAdded: "#50fa7b",
    toolDiffRemoved: "#ff5555",
    toolDiffContext: "#7f849c",
    syntaxComment: "#7f849c",
    syntaxKeyword: "#ff79c6",
    syntaxFunction: "#50fa7b",
    syntaxVariable: "#f8f8f2",
    syntaxString: "#f1fa8c",
    syntaxNumber: "#bd93f9",
    syntaxType: "#8bd5ff",
    syntaxOperator: "#ff79c6",
    syntaxPunctuation: "#f8f8f2",
    thinkingOff: "#7f849c",
    thinkingMinimal: "#8bd5ff",
    thinkingLow: "#50fa7b",
    thinkingMedium: "#f1fa8c",
    thinkingHigh: "#ffb86c",
    thinkingXhigh: "#ff5555",
    bashMode: "#50fa7b",
  };
  return new Theme(fgEntries, {
    selectedBg: "#313244",
    userMessageBg: "#1e1e2e",
    customMessageBg: "#1e1e2e",
    toolPendingBg: "#313244",
    toolSuccessBg: "#1f3d2b",
    toolErrorBg: "#3d1f2b",
  }, "truecolor", { name: "repochan-cli" });
}
