/** Safe protocol surface exposed by the package root. Mutations use entity actions. */
export {
  PROTOCOL_DIR,
  stamp,
  stampForPath,
  protocolRoot,
  root,
  stripProtocolPrefix,
  safeProtocolPath,
  exists,
  readJson,
  readJsonIfExists,
  readAnalysisArtifact,
  readPersonaArtifact,
  readInterviewArtifact,
  readReviewArtifact,
  readPersonaReviewArtifact,
  initProtocol,
  inspectProtocol,
  protocolVersionPath,
  relativeProtocolPath,
  orderDir,
  orderJsonPath,
  orderVersionsDir,
  orderReferencesDir,
  orderVersionDir,
  reviewJsonPath,
  reviewVersionsDir,
  personaReviewPath,
  personaReviewVersionsDir,
  personaCandidatesDir,
  personaCandidatePath,
  listJsonFiles,
  requireAnalysis,
  requirePersona,
  requireInterview,
  hasInterview,
} from "./index.js";
